# Generated by Django 5.2.1 on 2025-05-22 04:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calc', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Server',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_created=True)),
                ('name', models.CharField(max_length=100)),
                ('ip_address', models.CharField(max_length=100, null=True)),
                ('location', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('tag', models.CharField(max_length=50)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='ResourceUsage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_stamp', models.DateTimeField(auto_now_add=True)),
                ('cpu_usage_percent', models.FloatField(verbose_name=5.2)),
                ('ram_usage_percent', models.FloatField(verbose_name=5.2)),
                ('disk_usage_percent', models.FloatField(verbose_name=5.2)),
                ('app_usage_percent', models.FloatField(verbose_name=5.2)),
                ('server_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='calc.server')),
            ],
        ),
        migrations.CreateModel(
            name='NetworkTraffic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('incoming_traffic', models.FloatField(verbose_name=5.2)),
                ('server_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='calc.server')),
            ],
        ),
        migrations.CreateModel(
            name='Alert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField()),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('server_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='calc.server')),
            ],
        ),
    ]
