# Generated by Django 5.2.1 on 2025-05-23 04:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calc', '0002_server_resourceusage_networktraffic_alert'),
    ]

    operations = [
        migrations.AlterField(
            model_name='server',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
