# Generated by Django 5.2.1 on 2025-05-23 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calc', '0003_alter_server_created_at'),
    ]

    operations = [
        migrations.RenameField(
            model_name='alert',
            old_name='server_id',
            new_name='server',
        ),
        migrations.AddField(
            model_name='alert',
            name='severity',
            field=models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High')], default=1, max_length=10),
            preserve_default=False,
        ),
    ]
