# Generated by Django 5.2.1 on 2025-05-23 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calc', '0004_rename_server_id_alert_server_alert_severity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alert',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
